---
abstract: 'Find or build nasm, the netwide assembler'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Test::More: '0.94'
configure_requires:
  Alien::Base: '0.006'
  Alien::gmake: '0.02'
  Capture::Tiny: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-nasm
requires:
  Alien::Base: '0.006'
  base: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/Alien-nasm/issues
  homepage: http://perl.wdlabs.com/Alien-nasm
  repository: git://github.com/plicease/Alien-nasm.git
version: '0.04'
